# -*- coding: utf-8 -*-
"""aditya.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doomUCdv53Af7t7fGxtGX4LR64iwbysc
"""

import numpy as np
arr=np.array([10,20,30,40,50])
print("array:",arr)

import numpy as np
arr=np.array([10,20,30,40,50])
print("array:",arr)
print("no of element;",arr.size)
print("dimension:",arr.ndim)

import numpy as np
arr=np.array([[10,20,30],
             [40,50,60]])
print("2d array:",arr)

import numpy as np
arr=np.array([10,20,30,40,50])
print("array:",arr)
print("add;",arr+5)
print("sub:",arr-5)
print("mult:",arr*5)
print("div:",arr/2)

import numpy as np
arr=np.array([10,20,30,40,50])
print("1st ele:",arr[0])
print("3 ele:",arr[2])
print("lastele:",arr[-1])

import numpy as np
arr=np.array([10,20,30,40,50])
print("first three ele:",arr[0:3])
print("element from index 2:",arr[2:])

import numpy as np
marks=np.array([10,30,80,40,50])
print("marks:",marks)
print("sum:",np.sum(marks))
print("mean:",np.mean(marks))
print("maximum:",np.max(marks))
print("minimum:",np.min(marks))

import numpy as np

marks=np.array([65,70,75,80,85])

print("marks:",marks)

print("number of element:",marks.size)
print("dimension:",marks.ndim)

print("marks+5:",marks+5)
print("marks*2:",marks*2)

print("total marks:",np.sum(marks))
print("mean:",np.mean(marks))
print("maximum:",np.max(marks))
print("minimum:",np.min(marks))

